<?php
require_once __DIR__ . '/../config/db.php';

$pdo->exec("SET FOREIGN_KEY_CHECKS = 0");
$pdo->exec("TRUNCATE TABLE properties");
$pdo->exec("SET FOREIGN_KEY_CHECKS = 1");

$car_properties = [
    [
        'title' => 'Rolls-Royce Residences & Sky Villas',
        'description' => 'An architectural masterpiece of sheer opulence inspired by Rolls-Royce engineering. Features private helipad access, automated climate control, temperature-controlled infinity swimming pool, 6-car glass-enclosed showroom garage, and multi-layered biometric security.',
        'price' => 450000000.00,
        'location' => 'Maitama Extension, Abuja, Nigeria',
        'latitude' => 9.0765,
        'longitude' => 7.3986,
        'beds' => 6,
        'baths' => 7,
        'area_sqft' => 7500,
        'land_size_sqft' => 15000,
        'type' => 'sale',
        'category' => 'residential',
        'status' => 'active',
        'listing_status' => 'active',
        'image_url' => 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
        'video_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
        'agent_name' => 'Arc. Aminu Yola',
        'gallery_urls' => 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80,https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=800&q=80',
        'is_short_let' => 0
    ],
    [
        'title' => 'Maybach Executive Corporate Towers',
        'description' => 'Ultra-modern Grade-A luxury office complex honoring Maybach precision. Complete with centralized climate automation, executive penthouse suites, massive subterranean parking, dedicated optical fiber connectivity, and dual generator backup arrays.',
        'price' => 12500000.00,
        'location' => 'Victoria Island Commercial Hub, Lagos, Nigeria',
        'latitude' => 6.4281,
        'longitude' => 3.4219,
        'beds' => 0,
        'baths' => 6,
        'area_sqft' => 14000,
        'land_size_sqft' => 28000,
        'type' => 'rent',
        'category' => 'commercial',
        'status' => 'active',
        'listing_status' => 'active',
        'image_url' => 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
        'video_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
        'agent_name' => 'Dr. Ken Davies',
        'gallery_urls' => 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
        'is_short_let' => 0
    ],
    [
        'title' => 'Porsche Design Crest Estate',
        'description' => 'Sleek aerodynamic luxury smart villas featuring floor-to-ceiling glass curtain walls, private elevator access, integrated solar grid, and private tennis court facilities.',
        'price' => 290000000.00,
        'location' => 'Katampe Extension, Abuja, Nigeria',
        'latitude' => 9.1000,
        'longitude' => 7.4600,
        'beds' => 5,
        'baths' => 5,
        'area_sqft' => 6200,
        'land_size_sqft' => 12000,
        'type' => 'sale',
        'category' => 'residential',
        'status' => 'active',
        'listing_status' => 'active',
        'image_url' => 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80',
        'video_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
        'agent_name' => 'Arc. Aminu Yola',
        'gallery_urls' => 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80',
        'is_short_let' => 0
    ],
    [
        'title' => 'Bugatti Horizon Sky Villa & Suites',
        'description' => 'Exclusive ultra-speed luxury penthouse suites offering breathtaking skyline views, Italian leather furnishings, private concierge, and rooftop heated infinity spa.',
        'price' => 150000.00,
        'location' => 'Asokoro Heights, Abuja, Nigeria',
        'latitude' => 9.0400,
        'longitude' => 7.5200,
        'beds' => 3,
        'baths' => 3,
        'area_sqft' => 2200,
        'land_size_sqft' => 4400,
        'type' => 'rent',
        'category' => 'residential',
        'status' => 'active',
        'listing_status' => 'active',
        'image_url' => 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
        'video_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
        'agent_name' => 'Dr. Ken Davies',
        'gallery_urls' => 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80',
        'is_short_let' => 1
    ],
    [
        'title' => 'Bentley Continental Manor & Waterfront',
        'description' => 'Bespeak waterfront mansion with custom oak finishes, private yacht mooring slipway, intelligent security automation, and heated indoor swimming pool.',
        'price' => 380000000.00,
        'location' => 'Banana Island, Ikoyi, Lagos, Nigeria',
        'latitude' => 6.4633,
        'longitude' => 3.4475,
        'beds' => 6,
        'baths' => 8,
        'area_sqft' => 8200,
        'land_size_sqft' => 16400,
        'type' => 'sale',
        'category' => 'residential',
        'status' => 'active',
        'listing_status' => 'active',
        'image_url' => 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=80',
        'video_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
        'agent_name' => 'Arc. Aminu Yola',
        'gallery_urls' => 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=800&q=80',
        'is_short_let' => 0
    ],
    [
        'title' => 'Lamborghini Apex Agribusiness Hectares',
        'description' => 'Vast agricultural acreage with rich fertile loam assessed by our Agronomy division. Optimal terrain for high-yield mechanized farming routines. Complete boundary surveys and state C of O.',
        'price' => 25000000.00,
        'location' => 'Kofare Agric Zone, Yola, Nigeria',
        'latitude' => 9.2550,
        'longitude' => 12.4300,
        'beds' => 0,
        'baths' => 0,
        'area_sqft' => 435600,
        'land_size_sqft' => 871200,
        'type' => 'lease',
        'category' => 'land',
        'status' => 'active',
        'listing_status' => 'active',
        'image_url' => 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=800&q=80',
        'video_url' => '',
        'agent_name' => 'Dr. Ken Davies',
        'gallery_urls' => '',
        'is_short_let' => 0
    ],
    [
        'title' => 'Aston Martin Sovereign Court',
        'description' => 'Elegant lakeside luxury townhouses featuring bespoke craftsmanship, private boat docks, smart home automation, custom timber finishes, and private wine cellars.',
        'price' => 8500000.00,
        'location' => 'Jabi Lake District, Abuja, Nigeria',
        'latitude' => 9.0700,
        'longitude' => 7.4200,
        'beds' => 4,
        'baths' => 4,
        'area_sqft' => 3800,
        'land_size_sqft' => 7600,
        'type' => 'rent',
        'category' => 'residential',
        'status' => 'active',
        'listing_status' => 'active',
        'image_url' => 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=80',
        'video_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
        'agent_name' => 'Arc. Aminu Yola',
        'gallery_urls' => '',
        'is_short_let' => 0
    ],
    [
        'title' => 'Ferrari Velox Commercial Heights',
        'description' => 'Iconic glass-facade luxury commercial skyscraper with panoramic ocean view suites, high-end retail concourses, and automated subterranean parking facilities.',
        'price' => 550000000.00,
        'location' => 'Eko Atlantic City, Lagos, Nigeria',
        'latitude' => 6.4180,
        'longitude' => 3.4150,
        'beds' => 0,
        'baths' => 10,
        'area_sqft' => 25000,
        'land_size_sqft' => 50000,
        'type' => 'sale',
        'category' => 'commercial',
        'status' => 'active',
        'listing_status' => 'active',
        'image_url' => 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=800&q=80',
        'video_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
        'agent_name' => 'Dr. Ken Davies',
        'gallery_urls' => '',
        'is_short_let' => 0
    ]
];

$stmt = $pdo->prepare("
    INSERT INTO properties (title, description, price, location, latitude, longitude, beds, baths, area_sqft, land_size_sqft, type, category, status, listing_status, image_url, video_url, agent_name, gallery_urls, is_short_let, created_at)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW())
");

foreach ($car_properties as $p) {
    $stmt->execute([
        $p['title'],
        $p['description'],
        $p['price'],
        $p['location'],
        $p['latitude'],
        $p['longitude'],
        $p['beds'],
        $p['baths'],
        $p['area_sqft'],
        $p['land_size_sqft'],
        $p['type'],
        $p['category'],
        $p['status'],
        $p['listing_status'],
        $p['image_url'],
        $p['video_url'],
        $p['agent_name'],
        $p['gallery_urls'],
        $p['is_short_let']
    ]);
}

echo "Successfully populated " . count($car_properties) . " luxury car-themed properties!\n";
